[gemini]
GEMINI_API_KEY = "AIzaSyD3VVsj5G2Cjb-4w9PzNE9bgPX7UXDIlpk"

[email]
user = "placementgurus04@gmail.com"
password = "jdzn okvc dehn ayfu"
receiver = "placementgurus04@gmail.com"

[smtp]
host = "smtp.gmail.com"
port = 587